export const SET_PRODUCTS = "SET_PRODUCTS";
export const GET_PRODUCTS_SAGA = "GET_PRODUCTS_SAGA";
export const ADD_PRODUCT_IN_CART = "ADD_PRODUCT_IN_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
